### ISSUE TITLE
Hotkey support?

### ISSUE THREAD

**Issue by miriambrueckner** [CodeYan01/media-playlist-source#17]
Can the actions (start/stop/pause/next/previous) be bound to hotkeys? This would be awesome! So I could use this with my stream deck!

**Comment by miriambrueckner** [comment]
Sorry - I found it! (OBS newbie)

**Comment by miriambrueckner** [comment]
Reset and Stop are working - but next / previous is not working for me (I tried several custom hotkeys)
![image](https://github.com/CodeYan01/media-playlist-source/assets/24919429/68d127ba-e4bb-4e54-9f75-16fe23072598)

**Comment by CodeYan01** [comment]
Bug confirmed, also found other hotkey related issues. Will be fixed soon in the release, thanks for reporting!

**Comment by miriambrueckner** [comment]
I found the version 0.0.5 via your link but how can I use it (there is the master file but no windows installer?) (sorry I am a newbie with all this)

**Comment by CodeYan01** [comment]
It's not yet released, I have to fix the automatic build so a release will be made.

**Comment by CodeYan01** [comment]
Update released at https://github.com/CodeYan01/media-playlist-source/releases/tag/0.0.5

You will have to update the custom build to obs 30.0.0 from here https://github.com/CodeYan01/obs-studio/wiki
