### ISSUE TITLE
Crashing OBS

### ISSUE THREAD

**Issue by BioFUSION3k** [CodeYan01/media-playlist-source#24]
All I been doing is restoring default options, re-adding folder, click shuffle and bye bye obs. Sometimes I can get away with it, if I close the options window after each step, like add folder - close, open - click shuffle - close, etc. 

https://obsproject.com/logs/8Fahyb0nqMX1YK35

**Comment by CodeYan01** [comment]
Could you please try this build and see if you can reproduce the crash? https://github.com/CodeYan01/media-playlist-source/actions/runs/7592829244?pr=25

**Comment by CodeYan01** [comment]
Above build is merged into 0.0.6. Please report findings to see if the crashes are really fixed. Will be closed in 1 week if there's no response.
